name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.0.0
          - stable
          - beta
          - nightly
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust }}
    - run: cargo test

  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
        components: rustfmt
    - run: cargo fmt -- --check

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
    - run: cargo check

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
        components: clippy
    - run: cargo clippy -- --deny warnings

  codecov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
        components: llvm-tools-preview
    - run: cargo install cargo-llvm-cov
    - run: cargo llvm-cov --lcov --output-path lcov.info
    - uses: codecov/codecov-action@v2
      with:
        files: lcov.info
        fail_ci_if_error: true
